name: 💡 Feature Request
description: Suggest a new idea or improvement.
labels: ["feature", "status/needs-triage"]

body:
  - type: checkboxes
    id: search
    attributes:
      label: Search before suggesting
      options:
        - label: I have searched the existing issues and this feature has not been requested yet.
          required: true
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the project would this feature affect?
      multiple: true
      options:
        - Frontend (UI/UX)
        - Backend (API/Server)
        - Documentation
        - Core / Engine
        - Integration / Plugin
        - Other
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What do you want to happen?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case & Benefits
      description: Who would benefit from this and how?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other solutions you've thought of?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots.
    validations:
      required: false
